/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import("@docusaurus/plugin-content-docs/lib/types").Sidebars} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "TypeScriptのあらまし",
      collapsed: false,
      items: ["overview/README", "overview/features"],
    },
    {
      type: "category",
      label: "読んで学ぶTypeScript",
      collapsed: false,
      items: [
        "reference/README",
        {
          type: "category",
          label: "値・型・変数",
          items: [
            "reference/values-types-variables/let-and-const",
            "reference/values-types-variables/type-annotation",
            "reference/values-types-variables/vars-problems",
            "reference/values-types-variables/type-inference",
          ],
        },
      ],
    },
  ],
  writerSidebar: ["writing/getting-started", "writing/markdown"],
};
